Update main.py
I don't know what's wrong but it should work: 
ImportError: cannot import name 'WIDTH' from partially initialized module 'main' (most likely due to a circular import)